image: node:latest

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn
            - yarn lint:fix
            - yarn deploy
