service: screenshot-service

provider:
  name: aws
  region: eu-central-1
  stage: prod
  runtime: nodejs8.10
  memorySize: 3008
  timeout: 180
  environment:
    LOCAL: ${env:LOCAL}

functions:
  png:
    handler: src/handler.default
    events:
    - http:
        path: /
        method: get

plugins:
  - serverless-apigw-binary
  - serverless-offline

custom:
  apigwBinary:
    types:
    - '*/*'
